main.py
from crypt import methods
from unittest import result
from flask import Blueprint, render_template, session, redirect, request, flash, send_from_directory, jsonify
from flask_login import login_required, current_user
from app import uploadFolder, app
import os
from werkzeug.utils import secure_filename
import json
from models import User
import shutil
from controllers import UploadFile, CreateDirectory, ChangeDirectory

main = Blueprint("main", __name__, template_folder="templates")


def currentDirectory():
    return app.config["UPLOAD_FOLDER"] + session["current_dir"]


def getSize(startPath):
    totalSize = 0
    for dirpath, dirnames, filenames in os.walk(startPath):
        for file in filenames:
            filepath = os.path.join(dirpath, file)
            totalSize += os.path.getSize(filepath)
    return totalSize


def setCurrenturDirectory(directoryName):
    if directoryName == ".":
        session["current_dir"] = "/" + str(current_user.id)
    elif directoryName == "..":
        rem = session["current_dir"].split("/")
        if len(rem) > 0:
            rem.pop()
        session["current_dir"] = ""
        for file in rem[1:]:
            session["current_dir"] += "/" + file
    elif directoryName != "":
        session["current_dir"] += "/" + directoryName

    if len(session["current_dir"]) <= 1:
        session["current_dir"] = "/" + str(current_user.id)


@main.route("/")
def index():
    return render_template("index.html")


@main.context_processor
def user_auth():
    def is_logged_in():
        return current_user.is_authenticated
    return dict(is_logged_in=is_logged_in)


@main.route("/drive")
@login_required
def drive():
    if current_user.is_authenticated:
        if not "current_dir" in session:
            session["current_dir"] = "/" + str(current_user.id)
        return render_template("drive.html",
                               u_form=UploadFile(),
                               d_form=CreateDirectory(),
                               dir=session['current_dir'])
    return redirect("/login")


@main.route("/upload", methods=["POST"])
def uploadFile():
    if "file" in request.files:
        file = request.files["file"]
        filename = secure_filename(file.filename)
        file.save(os.path.join(currentDirectory(), filename))
    else:
        flash("Chyba pri nahrávaný súboru")
    return redirect("drive")


@main.route("/makedir", methods=["POST"])
def createDirectory():
    form = CreateDirectory(request.form)
    if form.validate_on_submit():
        directoryName = form.directoryName.data
        try:
            if not directoryName == "public":
                os.makedirs(currentDirectory() + "/" + directoryName)
            else:
                flash("Meno je rezervované")
                raise OSError("reserverd name")
        except OSError:
            flash("Nepodarilo sa vytvoriť priečinok")
    else:
        flash("Chyba")
    return redirect("drive")


@main.route("/getFiles", methods=["GET"])
def getFiles():
    files = []
    fileSize = []
    folders = []
    folderSize = []
    if current_user.is_authenticated:
        for file in os.listdir(currentDirectory()):
            path = currentDirectory() + "/" + file
            if file != ".DS_Store":
                if os.path.isfile(path):
                    files.append(file)
                    fileSize.append(os.stat(path).st_size)
                if os.path.isdir(path):
                    folders.append(file)
                    folderSize.append(getSize(path))

        files = json.dumps(files)
        fileSize = json.dumps(fileSize)
        folders = json.dumps(folders)
        folderSize = json.dumps(folderSize)

        return jsonify(
            files=files,
            fileSize=fileSize,
            folders=folders,
            folderSize=folderSize
        )
    else:
        return redirect("/login")


@main.route("/changedir", methods=["POST"])
def changeDir():
    if current_user.is_authenticated:
        directoryName = request.json["change_dir"]
        if (directoryName == ".." or directoryName == "." or directoryName in os.listdir(currentDirectory())) and os.path.isdir(currentDirectory() + "/" + directoryName):
            setCurrentDirectory(directoryName)
            return jsonify(result="success",
                           directory=str(session["current_dir"]),
                           current=currentDirectory()
                           )
        else:
            return jsonify(result="failed")


@main.route("/getfile/<filename>", methods=["GET"])
def getFile(filename):
    if current_user.is_authenticated:
        absolutePath = currentDirectory() + "/" + filename
        if filename in os.listdir(currentDirectory()) and os.path.isfile(absolutePath):
            return send_from_directory(currentDirectory(), filename)
    else:
        return render_template("404.html")


@main.route("/delete", methods=["POST"])
def deleteFile():
    if current_user.is_authenticated:
        try:
            filename = request.json["del_file"]
            absolutePath = currentDirectory() + "/" + filename
            if filename in os.listdir(currentDirectory()):
                if os.path.isfile(absolutePath):
                    os.unlink(currentDirectory() + "/" + filename)
                elif os.path.isdir(absolutePath):
                    shutil.rmtree(absolutePath)
                else:
                    return jsonify(result="failed")
                return jsonify(result="success")
            return jsonify(result="failed")
        except:
            return jsonify(result="failed")
    return redirect("/login")

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PolyShelf Admin</title>
</head>
<body>
    
</body>
</html>

templates/drive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/drive_style.css') }}">
    <title>PolyShelf</title>
</head>
<body>
    <h1><a href="/drive">PolyShelf</a></h1>
    <a href="/logout" class="logout">Odhlásiť sa</a>
    <div id="canvas">
        <div id="screen">
            <img src="{{url_for('static', filename='img/back.png') }}" onclick="cd('..')" alt="back" width="3%">
        
            <p>Súbory a priečinky:</p>
            <ul id="folders"></ul>
            <ul id="files"></ul>
            <ul id="file_sizes"></ul>
        </div>
    </div>


    <div class="buttons">
        <button id="newFile" class="newFile">Pridaj súbor</button>
        <button id="newFolder" class="newFolder">Nový priečinok</button>
    </div>

    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
          <span class="close">&times;</span>
          
          <div id="section2">
            <form action={{url_for("main.createDirectory")}} method="post">
                {{ d_form.hidden_tag() }}
                <p>
                {{ d_form.directoryName.label }}
                {{ d_form.directoryName(size=10) }}<br>
                </p>
                <p>{{ d_form.submit() }}</p>
            </form>
            </div>        
      
      </div>


    <div id="myModal1" class="modal1">

        <!-- Modal content -->
        <div class="modal-content1">
          <span class="close1">&times;</span>
          <div id="section1">
            <form action={{ url_for("main.uploadFile") }} method="post" enctype="multipart/form-data">
                {{ u_form.hidden_tag() }}
                <p>Choose a file to upload:</p>
                <p>{{ u_form.file() }}</p>
                <div float="left">
                {{ u_form.submit() }}
                </div>
            </form>
            </div>        
          </div>    
      </div>

      <script>
          var modal = document.getElementById("myModal");

          var btn = document.getElementById("newFile");

          var span = document.getElementsByClassName("close")[0];

          btn.onclick = function() {
            modal.style.display = "block";
          }

          span.onclick = function() {
            modal.style.display = "none";
          }

          window.onclick = function(event) {
            if (event.target == modal) {
              modal.style.display = "none";
            }
          } 
        
          var modal = document.getElementById("myModal1");

          var btn = document.getElementById("newFolder");

          var span = document.getElementsByClassName("close1")[0];

          btn.onclick = function() {
            modal.style.display = "block";
          }

          span.onclick = function() {
            modal.style.display = "none";
          }

          window.onclick = function(event) {
            if (event.target == modal) {
              modal.style.display = "none";
            }
          } 
      </script>

    <script type="text/javascript" src={{ url_for('static', filename="js/main2.js")}}></script>
</body>
</html>               

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PolyShelf</title>
</head>
<body>
    <h1>PolyShelf</h1>
    <div class="menu">
        <a href="/register" class="register">Registrácia</a>
        <a href="/login" class="login">Prihlásenie</a>
    </div>
    <center><h2>Vaše bezpečné úložisko</h2></center>
    <a href="/register" class="registerDown">Registrácia</a>
    <a href="/login" class="loginDown">Prihlásenie</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{{url_for('static', filename='css/login.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PolyShelf</title>
</head>
<body>
    <h1>PolyShelf</h1>
    <form method="POST" action="/login">
        <div class="field">
            <div class="control">
                <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <input class="input is-large" type="password" name="password" placeholder="Heslo">
            </div>
        </div>
        <div class="field">
            <label class="checkbox">
                <input type="checkbox">
                Pamataj si ma
            </label>
        </div>
        <button class="loginButton">Prihlásenie</button>
    </form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <link rel="stylesheet" href="{{url_for('static', filename='css/register.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PolyShelf</title>
</head>
<body>
    <h1>PolyShelf</h1>
    <form method="POST" action="/register">
        <div class="field">
            <div class="control">
                <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <input class="input is-large" type="password" name="password" placeholder="Password">
            </div>
        </div>

        <button class="registerButton">Registruj ma</button>
        <center><a href="/login", class="alreadyRegister">Už máte účet?</a></center>
    </form>
</body>
</html>